import { Timecode } from './types';

export const timecodes: Timecode[] = [
    {
        _id: "1",
        timeStart: 25,
        timeEnd: 28,
        title: 'Подсказка 1',
        text: 'Привет всем я денис ш Magna enim velit sunt consequat cupidatat pariatur. Enim deserunt adipisicing est aute. Ea enim ex Lorem ad elit consectetur qui velit. Ut ad id consequat enim ipsum cillum.Sunt esse consectetur sit aliquip culpa anim et duis dolor aliqua cillum enim. In irure sit occaecat sint pariatur nisi consectetur elit quis sit pariatur eu. Id cillum eiusmod velit ex laboris enim proident aliquip amet. Labore id ipsum non magna mollit sit enim cillum Lorem eiusmod velit ad officia labore. Ipsum ea id reprehenderit tempor exercitation excepteur. Sit pariatur cillum adipisicing sint labore nisi veniam nulla duis esse eu voluptate.In proident incididunt magna exercitation aute fugiat. Culpa aute consectetur irure irure veniam. Aute magna anim proident ea excepteur. Sit cupidatat do labore qui aute labore exercitation occaecat dolore proident et. Привет всем я денис ш Magna enim velit sunt consequat cupidatat pariatur. Enim deserunt adipisicing est aute. Ea enim ex Lorem ad elit consectetur qui velit. Ut ad id consequat enim ipsum cillum.Sunt esse consectetur sit aliquip culpa anim et duis dolor aliqua cillum enim. In irure sit occaecat sint pariatur nisi consectetur elit quis sit pariatur eu. Id cillum eiusmod velit ex laboris enim proident aliquip amet. Labore id ipsum non magna mollit sit enim cillum Lorem eiusmod velit ad officia labore. Ipsum ea id reprehenderit tempor exercitation excepteur. Sit pariatur cillum adipisicing sint labore nisi veniam nulla duis esse eu voluptate.In proident incididunt magna exercitation aute fugiat. Culpa aute consectetur irure irure veniam. Aute magna anim proident ea excepteur. Sit cupidatat do labore qui aute labore exercitation occaecat dolore proident et.'
    },
    {
        _id: "2",
        timeStart: 23,
        timeEnd: 26,
        title: 'Подсказка 2',
        text: 'Привет всем я денис ш Magna enim velit sunt consequat cupidatat pariatur. Enim deserunt adipisicing est aute. Ea enim ex Lorem ad elit consectetur qui velit. Ut ad id consequat enim ipsum cillum.Sunt esse consectetur sit aliquip culpa anim et duis dolor aliqua cillum enim. In irure sit occaecat sint pariatur nisi consectetur elit quis sit pariatur eu. Id cillum eiusmod velit ex laboris enim proident aliquip amet. Labore id ipsum non magna mollit sit enim cillum Lorem eiusmod velit ad officia labore. Ipsum ea id reprehenderit tempor exercitation excepteur. Sit pariatur cillum adipisicing sint labore nisi veniam nulla duis esse eu voluptate.In proident incididunt magna exercitation aute fugiat. Culpa aute consectetur irure irure veniam. Aute magna anim proident ea excepteur. Sit cupidatat do labore qui aute labore exercitation occaecat dolore proident et. Привет всем я денис ш Magna enim velit sunt consequat cupidatat pariatur. Enim deserunt adipisicing est aute. Ea enim ex Lorem ad elit consectetur qui velit. Ut ad id consequat enim ipsum cillum.Sunt esse consectetur sit aliquip culpa anim et duis dolor aliqua cillum enim. In irure sit occaecat sint pariatur nisi consectetur elit quis sit pariatur eu. Id cillum eiusmod velit ex laboris enim proident aliquip amet. Labore id ipsum non magna mollit sit enim cillum Lorem eiusmod velit ad officia labore. Ipsum ea id reprehenderit tempor exercitation excepteur. Sit pariatur cillum adipisicing sint labore nisi veniam nulla duis esse eu voluptate.In proident incididunt magna exercitation aute fugiat. Culpa aute consectetur irure irure veniam. Aute magna anim proident ea excepteur. Sit cupidatat do labore qui aute labore exercitation occaecat dolore proident et.'
    },
]